on:
  workflow_dispatch:
  push:
    branches: main


jobs:
  import-data:
  
    runs-on: ubuntu-latest
    container:
        image: ghcr.io/rocker-org/tidyverse:4.5
    strategy:
      fail-fast: false

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::rgbif 
            any::devtools
            any::janitor
            any::tidyr 
            any::rCAT           

      # - name: Install rCat
      #   run: |
      #     Rscript -e "pak::pkg_install('gistin/rCAT2')"

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Import data
        run: Rscript -e 'source("redlist_analysis.R")'

      - name: List what we built
        run: |
          ls -l
