on:
  workflow_dispatch:
  push:
    branches: main


jobs:
  import-data:
  
    runs-on: ubuntu-latest
    container:
        image: ghcr.io/rocker-org/tidyverse:4.5
    strategy:
      fail-fast: false

    steps:
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::rgbif 

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Import data
        run: Rscript -e 'source("redlist_analysis.R")'

      - name: List what we built
        run: |
          ls -l
