on:
  workflow_dispatch:
  push:
    branches: main


jobs:
  import-data:
    runs-on: rocker/tidyverse
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::rgbif 
            any::dplyr

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Import data
        run: Rscript -e 'source("run_scripts.R")'

      - name: List what we built
        run: |
          ls -l